# Site settings
title: Julien Maitrehenry
tagline: Web developper and devops
email: julien.maitrehenry@me.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m a professional web developer specialize in DevOps and Agile practices. 
  I love building cloud system and monitoring it.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "https://www.jmaitrehenry.ca" # the base hostname & protocol for your site
url: ""
logourl: /assets/images/logo.png # Site logo
author: "Julien Maitrehenry"
author_thumbnail: "http://www.gravatar.com/avatar/d1ae7b5fe133a53f8a5b1dc5640e4b76?s=200" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: jmaitrehenry
    twitter: jmaitrehenry
    linkedin: jmaitrehenry

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: jmaitrehenry-blog

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: "UA-64642121-1"
  google_webmaster_key: "hmAkvVqWPWFz6ndNRm-2AL4EJw0Op6jsQwwP_IBAmkk"

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-paginate
